kind: Pod
apiVersion: v1
metadata:
  name: nginx
spec:
  containers:
    - name: mywebserver
      image: nginx
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: azure-managed-disk
