apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: mywebserver.b6ca4e1ef77140cba20a.westeurope.aksapp.io
    http:
      paths:
      - backend:
          serviceName: web-svc
          servicePort: 80
        path: /